/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ozen;

/**
 * CALCULADORA DE MATRIZES 2x2
 * @author bruno ozen
 */
public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    int operacao;
    int a[][] = new int[][]{{0, 0},{0, 0}};
    int b[][] = new int[][]{{0, 0},{0, 0}};
    int c[][] = new int[][]{{0, 0},{0, 0}};
    public TelaCalculadora() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a11 = new javax.swing.JSpinner();
        a21 = new javax.swing.JSpinner();
        a22 = new javax.swing.JSpinner();
        b11 = new javax.swing.JSpinner();
        a12 = new javax.swing.JSpinner();
        b12 = new javax.swing.JSpinner();
        b21 = new javax.swing.JSpinner();
        b22 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        lblOperacao = new javax.swing.JLabel();
        btnMultiplicacao = new javax.swing.JButton();
        c11 = new javax.swing.JLabel();
        c12 = new javax.swing.JLabel();
        c21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        c22 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSoma = new javax.swing.JButton();
        btnSubtracao = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                a11StateChanged(evt);
            }
        });
        getContentPane().add(a11, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 167, 38, 39));

        a21.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                a21StateChanged(evt);
            }
        });
        getContentPane().add(a21, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 224, 38, 39));

        a22.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                a22StateChanged(evt);
            }
        });
        getContentPane().add(a22, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 224, 38, 39));

        b11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                b11StateChanged(evt);
            }
        });
        getContentPane().add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 167, 38, 39));

        a12.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                a12StateChanged(evt);
            }
        });
        getContentPane().add(a12, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 167, 38, 39));

        b12.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                b12StateChanged(evt);
            }
        });
        getContentPane().add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 167, 38, 39));

        b21.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                b21StateChanged(evt);
            }
        });
        getContentPane().add(b21, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 224, 38, 39));

        b22.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                b22StateChanged(evt);
            }
        });
        getContentPane().add(b22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 224, 38, 39));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("=");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 198, -1, -1));

        lblOperacao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblOperacao.setForeground(new java.awt.Color(153, 0, 0));
        lblOperacao.setText("+");
        getContentPane().add(lblOperacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 198, -1, -1));

        btnMultiplicacao.setText("x");
        btnMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiplicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 40, 40));

        c11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        c11.setText("0");
        getContentPane().add(c11, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 166, -1, -1));

        c12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        c12.setText("0");
        getContentPane().add(c12, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 166, -1, -1));

        c21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        c21.setText("0");
        getContentPane().add(c21, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 232, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("<html><b>CALCULADORA DE MATRIZES 2x2</b></html>");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        c22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        c22.setText("0");
        getContentPane().add(c22, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 232, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("OPERAÇÃO:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        btnSoma.setText("+");
        btnSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 40, 40));

        btnSubtracao.setText("-");
        btnSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtracaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubtracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 40, 40));

        jLabel9.setText("By Bruno Özen ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacaoActionPerformed
        // TODO add your handling code here:
        lblOperacao.setText("x");
        operacao = 2; 
        c = operar(a, b);
        atualizaMatriz();
    }//GEN-LAST:event_btnMultiplicacaoActionPerformed

    private void btnSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomaActionPerformed
        // TODO add your handling code here:
        lblOperacao.setText("+");
        operacao = 0;
        c = operar(a, b);
        atualizaMatriz();
    }//GEN-LAST:event_btnSomaActionPerformed

    private void btnSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtracaoActionPerformed
        // TODO add your handling code here:
        lblOperacao.setText("-");
        operacao = 1;
        c = operar(a, b);
        atualizaMatriz();
    }//GEN-LAST:event_btnSubtracaoActionPerformed

    private void a11StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_a11StateChanged
        // TODO add your handling code here:
        a[0][0] = Integer.parseInt(a11.getValue().toString());
        c = operar(a, b);
        atualizaMatriz();
    }//GEN-LAST:event_a11StateChanged

    private void a12StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_a12StateChanged
        // TODO add your handling code here:
        a[0][1] = Integer.parseInt(a12.getValue().toString());
        c = operar(a, b);
        atualizaMatriz();
    }//GEN-LAST:event_a12StateChanged

    private void a21StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_a21StateChanged
        // TODO add your handling code here:
        a[1][0] = Integer.parseInt(a21.getValue().toString());
        c = operar(a, b);
        atualizaMatriz();
    }//GEN-LAST:event_a21StateChanged

    private void a22StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_a22StateChanged
        // TODO add your handling code here:
        a[1][1] = Integer.parseInt(a22.getValue().toString());
        c = operar(a, b);
        atualizaMatriz();
    }//GEN-LAST:event_a22StateChanged

    private void b11StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_b11StateChanged
        // TODO add your handling code here:
        b[0][0] = Integer.parseInt(b11.getValue().toString());
        c = operar(a, b);
        atualizaMatriz();
    }//GEN-LAST:event_b11StateChanged

    private void b12StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_b12StateChanged
        // TODO add your handling code here:
        b[0][1] = Integer.parseInt(b12.getValue().toString());
        c = operar(a, b);
        atualizaMatriz();
    }//GEN-LAST:event_b12StateChanged

    private void b21StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_b21StateChanged
        // TODO add your handling code here:
        b[1][0] = Integer.parseInt(b21.getValue().toString());
        c = operar(a, b);
        atualizaMatriz();
    }//GEN-LAST:event_b21StateChanged

    private void b22StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_b22StateChanged
        // TODO add your handling code here:
        b[1][1] = Integer.parseInt(b22.getValue().toString());
        c = operar(a, b);
        atualizaMatriz();
    }//GEN-LAST:event_b22StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }
    public int [][] operar(int a[][], int b[][]){
        int resultado[][] = new int[2][2];
        switch(operacao){
            case 0:
                for(int i = 0; i<2; i++){
                    for(int j = 0; j<2; j++){
                        resultado[i][j] = a[i][j]+ b[i][j];
                    }
                }
                break;
            case 1:
                for(int i = 0; i<2; i++){
                    for(int j = 0; j<2; j++){
                        resultado[i][j] = a[i][j]- b[i][j];
                    }
                }
                break;
            case 2:
                resultado[0][0] = a[0][0]*b[0][0]+a[0][1]*b[1][0];
                resultado[0][1] = a[0][0]*b[0][1]+a[0][1]*b[1][1];
                resultado[1][0] = a[1][0]*b[0][0]+a[1][1]*b[1][0];
                resultado[1][1] = a[1][0]*b[0][1]+a[1][1]*b[1][1];
                break;
        }
        return resultado;
    }
    public void atualizaMatriz(){
        c11.setText(Integer.toString(c[0][0]));
        c12.setText(Integer.toString(c[0][1]));
        c21.setText(Integer.toString(c[1][0]));
        c22.setText(Integer.toString(c[1][1]));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner a11;
    private javax.swing.JSpinner a12;
    private javax.swing.JSpinner a21;
    private javax.swing.JSpinner a22;
    private javax.swing.JSpinner b11;
    private javax.swing.JSpinner b12;
    private javax.swing.JSpinner b21;
    private javax.swing.JSpinner b22;
    private javax.swing.JButton btnMultiplicacao;
    private javax.swing.JButton btnSoma;
    private javax.swing.JButton btnSubtracao;
    private javax.swing.JLabel c11;
    private javax.swing.JLabel c12;
    private javax.swing.JLabel c21;
    private javax.swing.JLabel c22;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblOperacao;
    // End of variables declaration//GEN-END:variables
}
